/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../../common";
import type {
  InitializableUpgradeabilityProxy,
  InitializableUpgradeabilityProxyInterface,
} from "../../../../dependencies/openzeppelin/upgradeability/InitializableUpgradeabilityProxy";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "implementation",
        type: "address",
      },
    ],
    name: "Upgraded",
    type: "event",
  },
  {
    stateMutability: "payable",
    type: "fallback",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_logic",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "_data",
        type: "bytes",
      },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506103b4806100206000396000f3fe60806040526004361061001e5760003560e01c8063d1f5789414610028575b61002661003b565b005b610026610036366004610218565b61005b565b61005961005460008051602061035f8339815191525490565b61014b565b565b600061007360008051602061035f8339815191525490565b6001600160a01b03161461008657600080fd5b6100b160017f360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbd6102e8565b60008051602061035f833981519152146100cd576100cd61030d565b6100d68261016f565b805115610147576000826001600160a01b0316826040516100f79190610323565b600060405180830381855af49150503d8060008114610132576040519150601f19603f3d011682016040523d82523d6000602084013e610137565b606091505b505090508061014557600080fd5b505b5050565b3660008037600080366000845af43d6000803e80801561016a573d6000f35b3d6000fd5b6001600160a01b0381163b6101f05760405162461bcd60e51b815260206004820152603b60248201527f43616e6e6f742073657420612070726f787920696d706c656d656e746174696f60448201527f6e20746f2061206e6f6e2d636f6e747261637420616464726573730000000000606482015260840160405180910390fd5b60008051602061035f83398151915255565b634e487b7160e01b600052604160045260246000fd5b6000806040838503121561022b57600080fd5b82356001600160a01b038116811461024257600080fd5b9150602083013567ffffffffffffffff8082111561025f57600080fd5b818501915085601f83011261027357600080fd5b81358181111561028557610285610202565b604051601f8201601f19908116603f011681019083821181831017156102ad576102ad610202565b816040528281528860208487010111156102c657600080fd5b8260208601602083013760006020848301015280955050505050509250929050565b60008282101561030857634e487b7160e01b600052601160045260246000fd5b500390565b634e487b7160e01b600052600160045260246000fd5b6000825160005b81811015610344576020818601810151858301520161032a565b81811115610353576000828501525b50919091019291505056fe360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbca264697066735822122062b714d6151123c0ee32dc0aace68c941f78ee26e04df6722f122f3c95ae44dc64736f6c634300080a0033";

type InitializableUpgradeabilityProxyConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: InitializableUpgradeabilityProxyConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class InitializableUpgradeabilityProxy__factory extends ContractFactory {
  constructor(...args: InitializableUpgradeabilityProxyConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<InitializableUpgradeabilityProxy> {
    return super.deploy(
      overrides || {}
    ) as Promise<InitializableUpgradeabilityProxy>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): InitializableUpgradeabilityProxy {
    return super.attach(address) as InitializableUpgradeabilityProxy;
  }
  override connect(signer: Signer): InitializableUpgradeabilityProxy__factory {
    return super.connect(signer) as InitializableUpgradeabilityProxy__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): InitializableUpgradeabilityProxyInterface {
    return new utils.Interface(
      _abi
    ) as InitializableUpgradeabilityProxyInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): InitializableUpgradeabilityProxy {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as InitializableUpgradeabilityProxy;
  }
}
