/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { I_account, I_accountInterface } from "../../interfaces/I_account";

const _abi = [
  {
    inputs: [],
    name: "ADDRESSES_PROVIDER",
    outputs: [
      {
        internalType: "contract i_addresses_provider",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "create_account",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "pub_key",
        type: "address",
      },
    ],
    name: "get_account_by_address",
    outputs: [
      {
        components: [
          {
            internalType: "bool",
            name: "is_init",
            type: "bool",
          },
          {
            internalType: "uint256",
            name: "inviter_id",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "xp",
            type: "uint256",
          },
          {
            internalType: "address[]",
            name: "pub_keys",
            type: "address[]",
          },
          {
            internalType: "uint256[2]",
            name: "affiliates",
            type: "uint256[2]",
          },
          {
            internalType: "string",
            name: "metadata",
            type: "string",
          },
          {
            components: [
              {
                internalType: "uint256",
                name: "_value",
                type: "uint256",
              },
            ],
            internalType: "struct Counters.Counter",
            name: "invite_buyer",
            type: "tuple",
          },
          {
            components: [
              {
                internalType: "uint256",
                name: "_value",
                type: "uint256",
              },
            ],
            internalType: "struct Counters.Counter",
            name: "invite_seller",
            type: "tuple",
          },
        ],
        internalType: "struct l_data_types.s_account",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "account_id",
        type: "uint256",
      },
    ],
    name: "get_account_by_id",
    outputs: [
      {
        components: [
          {
            internalType: "bool",
            name: "is_init",
            type: "bool",
          },
          {
            internalType: "uint256",
            name: "inviter_id",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "xp",
            type: "uint256",
          },
          {
            internalType: "address[]",
            name: "pub_keys",
            type: "address[]",
          },
          {
            internalType: "uint256[2]",
            name: "affiliates",
            type: "uint256[2]",
          },
          {
            internalType: "string",
            name: "metadata",
            type: "string",
          },
          {
            components: [
              {
                internalType: "uint256",
                name: "_value",
                type: "uint256",
              },
            ],
            internalType: "struct Counters.Counter",
            name: "invite_buyer",
            type: "tuple",
          },
          {
            components: [
              {
                internalType: "uint256",
                name: "_value",
                type: "uint256",
              },
            ],
            internalType: "struct Counters.Counter",
            name: "invite_seller",
            type: "tuple",
          },
        ],
        internalType: "struct l_data_types.s_account",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "pub_key",
        type: "address",
      },
    ],
    name: "get_account_id_by_address",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "get_accounts_count",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "get_accounts_list",
    outputs: [
      {
        components: [
          {
            internalType: "bool",
            name: "is_init",
            type: "bool",
          },
          {
            internalType: "uint256",
            name: "inviter_id",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "xp",
            type: "uint256",
          },
          {
            internalType: "address[]",
            name: "pub_keys",
            type: "address[]",
          },
          {
            internalType: "uint256[2]",
            name: "affiliates",
            type: "uint256[2]",
          },
          {
            internalType: "string",
            name: "metadata",
            type: "string",
          },
          {
            components: [
              {
                internalType: "uint256",
                name: "_value",
                type: "uint256",
              },
            ],
            internalType: "struct Counters.Counter",
            name: "invite_buyer",
            type: "tuple",
          },
          {
            components: [
              {
                internalType: "uint256",
                name: "_value",
                type: "uint256",
              },
            ],
            internalType: "struct Counters.Counter",
            name: "invite_seller",
            type: "tuple",
          },
        ],
        internalType: "struct l_data_types.s_account[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "get_pub_keys_count",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class I_account__factory {
  static readonly abi = _abi;
  static createInterface(): I_accountInterface {
    return new utils.Interface(_abi) as I_accountInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): I_account {
    return new Contract(address, _abi, signerOrProvider) as I_account;
  }
}
