/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  I_addresses_provider,
  I_addresses_providerInterface,
} from "../../interfaces/I_addresses_provider";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "old_address",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "new_address",
        type: "address",
      },
    ],
    name: "ev_acl_admin_updated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "old_address",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "new_address",
        type: "address",
      },
    ],
    name: "ev_acl_manager_updated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "id",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "old_address",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "new_address",
        type: "address",
      },
    ],
    name: "ev_address_set",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "id",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "proxy_address",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "old_implementation_address",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "new_implementation_address",
        type: "address",
      },
    ],
    name: "ev_address_set_as_proxy",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "old_address",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "new_address",
        type: "address",
      },
    ],
    name: "ev_data_provider_updated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "old_address",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "new_address",
        type: "address",
      },
    ],
    name: "ev_escrow_updated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "old_address",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "new_address",
        type: "address",
      },
    ],
    name: "ev_gig_updated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "string",
        name: "old_marketplace_id",
        type: "string",
      },
      {
        indexed: true,
        internalType: "string",
        name: "new_marketplace_id",
        type: "string",
      },
    ],
    name: "ev_marketplace_id_set",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "old_address",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "new_address",
        type: "address",
      },
    ],
    name: "ev_offer_updated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "old_address",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "new_address",
        type: "address",
      },
    ],
    name: "ev_price_oracle_updated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "old_address",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "new_address",
        type: "address",
      },
    ],
    name: "ev_protocol_configurator_updated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "id",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "proxy_address",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "implementation_address",
        type: "address",
      },
    ],
    name: "ev_proxy_created",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "old_address",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "new_address",
        type: "address",
      },
    ],
    name: "ev_user_updated",
    type: "event",
  },
  {
    inputs: [],
    name: "get_acl_admin",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "get_acl_manager",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "id",
        type: "bytes32",
      },
    ],
    name: "get_address",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "get_data_provider",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "get_escrow",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "get_gig",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "get_marketplace_id",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "get_offer",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "get_price_oracle",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "get_protocol_configurator",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "get_user",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "new_acl_admin",
        type: "address",
      },
    ],
    name: "set_acl_admin",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "new_acl_manager",
        type: "address",
      },
    ],
    name: "set_acl_manager",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "id",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "new_address",
        type: "address",
      },
    ],
    name: "set_address",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "id",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "new_implementation_address",
        type: "address",
      },
    ],
    name: "set_address_as_proxy",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "new_data_provider",
        type: "address",
      },
    ],
    name: "set_data_provider",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "new_escrow_impl",
        type: "address",
      },
    ],
    name: "set_escrow_impl",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "new_gig_impl",
        type: "address",
      },
    ],
    name: "set_gig_impl",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "new_marketplace_id",
        type: "string",
      },
    ],
    name: "set_marketplace_id",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "new_offer_impl",
        type: "address",
      },
    ],
    name: "set_offer_impl",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "new_price_oracle",
        type: "address",
      },
    ],
    name: "set_price_oracle",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "new_pool_configurator_impl",
        type: "address",
      },
    ],
    name: "set_protocol_configurator_impl",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "new_user_impl",
        type: "address",
      },
    ],
    name: "set_user_impl",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class I_addresses_provider__factory {
  static readonly abi = _abi;
  static createInterface(): I_addresses_providerInterface {
    return new utils.Interface(_abi) as I_addresses_providerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): I_addresses_provider {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as I_addresses_provider;
  }
}
