/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../../common";
import type {
  L_account_data_logic,
  L_account_data_logicInterface,
} from "../../../../protocol/libraries/logics/L_account_data_logic";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "account_id",
        type: "uint256",
      },
      {
        components: [
          {
            internalType: "bool",
            name: "is_init",
            type: "bool",
          },
          {
            internalType: "uint256",
            name: "inviter_id",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "xp",
            type: "uint256",
          },
          {
            internalType: "address[]",
            name: "pub_keys",
            type: "address[]",
          },
          {
            internalType: "uint256[2]",
            name: "affiliates",
            type: "uint256[2]",
          },
          {
            internalType: "string",
            name: "metadata",
            type: "string",
          },
          {
            components: [
              {
                internalType: "uint256",
                name: "_value",
                type: "uint256",
              },
            ],
            internalType: "struct Counters.Counter",
            name: "invite_buyer",
            type: "tuple",
          },
          {
            components: [
              {
                internalType: "uint256",
                name: "_value",
                type: "uint256",
              },
            ],
            internalType: "struct Counters.Counter",
            name: "invite_seller",
            type: "tuple",
          },
        ],
        indexed: false,
        internalType: "struct l_data_types.s_account",
        name: "account",
        type: "tuple",
      },
    ],
    name: "ev_account_data_updated",
    type: "event",
  },
];

const _bytecode =
  "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea26469706673582212200cde85105da33d47bfee20d518a8de05264c6f72461d9763aeb46aef7ff0fa3264736f6c634300080a0033";

type L_account_data_logicConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: L_account_data_logicConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class L_account_data_logic__factory extends ContractFactory {
  constructor(...args: L_account_data_logicConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<L_account_data_logic> {
    return super.deploy(overrides || {}) as Promise<L_account_data_logic>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): L_account_data_logic {
    return super.attach(address) as L_account_data_logic;
  }
  override connect(signer: Signer): L_account_data_logic__factory {
    return super.connect(signer) as L_account_data_logic__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): L_account_data_logicInterface {
    return new utils.Interface(_abi) as L_account_data_logicInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): L_account_data_logic {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as L_account_data_logic;
  }
}
