/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export interface L_errorsInterface extends utils.Interface {
  functions: {
    "ACCOUNT_ALREADY_CREATED()": FunctionFragment;
    "ACL_ADMIN_CANNOT_BE_ZERO()": FunctionFragment;
    "ADDRESSES_PROVIDER_ALREADY_ADDED()": FunctionFragment;
    "ADDRESSES_PROVIDER_NOT_REGISTERED()": FunctionFragment;
    "ADDRESS_ALREADY_LINKED_TO_ACCOUNT()": FunctionFragment;
    "CALLER_NOT_PROTOCOL_ADMIN()": FunctionFragment;
    "GIG_ALREADY_CREATED()": FunctionFragment;
    "INVALID_ACCOUNT_ID()": FunctionFragment;
    "INVALID_ADDRESSES_PROVIDER()": FunctionFragment;
    "INVALID_ADDRESSES_PROVIDER_ID()": FunctionFragment;
    "INVALID_GIG_ID()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "ACCOUNT_ALREADY_CREATED"
      | "ACL_ADMIN_CANNOT_BE_ZERO"
      | "ADDRESSES_PROVIDER_ALREADY_ADDED"
      | "ADDRESSES_PROVIDER_NOT_REGISTERED"
      | "ADDRESS_ALREADY_LINKED_TO_ACCOUNT"
      | "CALLER_NOT_PROTOCOL_ADMIN"
      | "GIG_ALREADY_CREATED"
      | "INVALID_ACCOUNT_ID"
      | "INVALID_ADDRESSES_PROVIDER"
      | "INVALID_ADDRESSES_PROVIDER_ID"
      | "INVALID_GIG_ID"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "ACCOUNT_ALREADY_CREATED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ACL_ADMIN_CANNOT_BE_ZERO",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ADDRESSES_PROVIDER_ALREADY_ADDED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ADDRESSES_PROVIDER_NOT_REGISTERED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ADDRESS_ALREADY_LINKED_TO_ACCOUNT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CALLER_NOT_PROTOCOL_ADMIN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GIG_ALREADY_CREATED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INVALID_ACCOUNT_ID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INVALID_ADDRESSES_PROVIDER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INVALID_ADDRESSES_PROVIDER_ID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INVALID_GIG_ID",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "ACCOUNT_ALREADY_CREATED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ACL_ADMIN_CANNOT_BE_ZERO",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ADDRESSES_PROVIDER_ALREADY_ADDED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ADDRESSES_PROVIDER_NOT_REGISTERED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ADDRESS_ALREADY_LINKED_TO_ACCOUNT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "CALLER_NOT_PROTOCOL_ADMIN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GIG_ALREADY_CREATED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INVALID_ACCOUNT_ID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INVALID_ADDRESSES_PROVIDER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INVALID_ADDRESSES_PROVIDER_ID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INVALID_GIG_ID",
    data: BytesLike
  ): Result;

  events: {};
}

export interface L_errors extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: L_errorsInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    ACCOUNT_ALREADY_CREATED(overrides?: CallOverrides): Promise<[string]>;

    ACL_ADMIN_CANNOT_BE_ZERO(overrides?: CallOverrides): Promise<[string]>;

    ADDRESSES_PROVIDER_ALREADY_ADDED(
      overrides?: CallOverrides
    ): Promise<[string]>;

    ADDRESSES_PROVIDER_NOT_REGISTERED(
      overrides?: CallOverrides
    ): Promise<[string]>;

    ADDRESS_ALREADY_LINKED_TO_ACCOUNT(
      overrides?: CallOverrides
    ): Promise<[string]>;

    CALLER_NOT_PROTOCOL_ADMIN(overrides?: CallOverrides): Promise<[string]>;

    GIG_ALREADY_CREATED(overrides?: CallOverrides): Promise<[string]>;

    INVALID_ACCOUNT_ID(overrides?: CallOverrides): Promise<[string]>;

    INVALID_ADDRESSES_PROVIDER(overrides?: CallOverrides): Promise<[string]>;

    INVALID_ADDRESSES_PROVIDER_ID(overrides?: CallOverrides): Promise<[string]>;

    INVALID_GIG_ID(overrides?: CallOverrides): Promise<[string]>;
  };

  ACCOUNT_ALREADY_CREATED(overrides?: CallOverrides): Promise<string>;

  ACL_ADMIN_CANNOT_BE_ZERO(overrides?: CallOverrides): Promise<string>;

  ADDRESSES_PROVIDER_ALREADY_ADDED(overrides?: CallOverrides): Promise<string>;

  ADDRESSES_PROVIDER_NOT_REGISTERED(overrides?: CallOverrides): Promise<string>;

  ADDRESS_ALREADY_LINKED_TO_ACCOUNT(overrides?: CallOverrides): Promise<string>;

  CALLER_NOT_PROTOCOL_ADMIN(overrides?: CallOverrides): Promise<string>;

  GIG_ALREADY_CREATED(overrides?: CallOverrides): Promise<string>;

  INVALID_ACCOUNT_ID(overrides?: CallOverrides): Promise<string>;

  INVALID_ADDRESSES_PROVIDER(overrides?: CallOverrides): Promise<string>;

  INVALID_ADDRESSES_PROVIDER_ID(overrides?: CallOverrides): Promise<string>;

  INVALID_GIG_ID(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    ACCOUNT_ALREADY_CREATED(overrides?: CallOverrides): Promise<string>;

    ACL_ADMIN_CANNOT_BE_ZERO(overrides?: CallOverrides): Promise<string>;

    ADDRESSES_PROVIDER_ALREADY_ADDED(
      overrides?: CallOverrides
    ): Promise<string>;

    ADDRESSES_PROVIDER_NOT_REGISTERED(
      overrides?: CallOverrides
    ): Promise<string>;

    ADDRESS_ALREADY_LINKED_TO_ACCOUNT(
      overrides?: CallOverrides
    ): Promise<string>;

    CALLER_NOT_PROTOCOL_ADMIN(overrides?: CallOverrides): Promise<string>;

    GIG_ALREADY_CREATED(overrides?: CallOverrides): Promise<string>;

    INVALID_ACCOUNT_ID(overrides?: CallOverrides): Promise<string>;

    INVALID_ADDRESSES_PROVIDER(overrides?: CallOverrides): Promise<string>;

    INVALID_ADDRESSES_PROVIDER_ID(overrides?: CallOverrides): Promise<string>;

    INVALID_GIG_ID(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    ACCOUNT_ALREADY_CREATED(overrides?: CallOverrides): Promise<BigNumber>;

    ACL_ADMIN_CANNOT_BE_ZERO(overrides?: CallOverrides): Promise<BigNumber>;

    ADDRESSES_PROVIDER_ALREADY_ADDED(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    ADDRESSES_PROVIDER_NOT_REGISTERED(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    ADDRESS_ALREADY_LINKED_TO_ACCOUNT(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    CALLER_NOT_PROTOCOL_ADMIN(overrides?: CallOverrides): Promise<BigNumber>;

    GIG_ALREADY_CREATED(overrides?: CallOverrides): Promise<BigNumber>;

    INVALID_ACCOUNT_ID(overrides?: CallOverrides): Promise<BigNumber>;

    INVALID_ADDRESSES_PROVIDER(overrides?: CallOverrides): Promise<BigNumber>;

    INVALID_ADDRESSES_PROVIDER_ID(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    INVALID_GIG_ID(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    ACCOUNT_ALREADY_CREATED(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ACL_ADMIN_CANNOT_BE_ZERO(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ADDRESSES_PROVIDER_ALREADY_ADDED(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ADDRESSES_PROVIDER_NOT_REGISTERED(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ADDRESS_ALREADY_LINKED_TO_ACCOUNT(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    CALLER_NOT_PROTOCOL_ADMIN(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    GIG_ALREADY_CREATED(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    INVALID_ACCOUNT_ID(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    INVALID_ADDRESSES_PROVIDER(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    INVALID_ADDRESSES_PROVIDER_ID(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    INVALID_GIG_ID(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
