/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as account from "./account";
export type { account };
import type * as configuration from "./configuration";
export type { configuration };
import type * as gig from "./gig";
export type { gig };
import type * as libraries from "./libraries";
export type { libraries };
