/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as aave from "./aave";
export type { aave };
import type * as openzeppelin from "./openzeppelin";
export type { openzeppelin };
